### ISSUE TITLE
Accumulating amounts of Failed processing a proof: Verification equation was not satisfied

### ISSUE THREAD

**Issue by najamelan** [crev-dev/cargo-crev#333] opened 2020-04-25 20:29 UTC
cargo-crev 0.16.1 installed with cargo install on Arch Linux. This is a fresh install with nothing run other than `cargo crev crate verify` and a bunch of `cargo crev repo fetch https://...`. 

I wanted to give cargo-crev another try, so I skimmed through github in the hopes of getting some reviews, as otherwise it just seems to be rather empty and not very useful. When starting to import reviews this happened. These messages accumulate and are printed on every run. I'm not quite sure what they mean exactly, but it might be that cargo-crev imports proofs that aren't valid and then keeps printing errors for them on every run. The first time the error comes up is with https://github.com/dmerejkowsky/crev-proofs.git:
```
 !  /d/d/c/async_executors    cargo crev repo fetch url https://github.com/BurntSushi/crev-proofs.git
Fetching https://github.com/BurntSushi/crev-proofs.git... OK; 1 new trust proofs; 6 new package reviews
Found proofs from:
       7 VylyTuk8CMGqIxgHixWaqfiUn3xZyzOA1wFrQ0sR1As
 /d/d/c/async_executors    cargo crev repo fetch url https://github.com/MaulingMonkey/crev-proofs.git
Fetching https://github.com/MaulingMonkey/crev-proofs.git... OK; 2 new trust proofs; 136 new package reviews
Found proofs from:
     138 6OZqHXqyUAF57grEY7IVMjRljdd9dgDxiNtr1NF1BdY
 /d/d/c/async_executors    cargo crev repo fetch url https://github.com/huitseeker/crev-proofs.git
Fetching https://github.com/huitseeker/crev-proofs.git... OK; 4 new package reviews
Found proofs from:
       4 5XSQsMDSEeY_uFOh9UOkkUiq8nt8ThA5ZJCHaxcuhjM
 /d/d/c/async_executors    cargo crev repo fetch url https://github.com/Alxandr/crev-proofs.git
Fetching https://github.com/Alxandr/crev-proofs.git... OK; 1 new trust proofs; 1 new package reviews
Found proofs from:
       2 JphL96Wm0VIidX6xWtAv7JmZ3sKn1R-IyjBrQSXYvaQ
 /d/d/c/async_executors    cargo crev repo fetch url https://github.com/lo48576/crev-proofs.git
Fetching https://github.com/lo48576/crev-proofs.git... OK; 3 new trust proofs; 7 new package reviews
Found proofs from:
      10 wO-tKiJm4SRMJeJSAo_gT54GAoY2KhwMGHzEZUcTmbk
 /d/d/c/async_executors    cargo crev repo fetch url https://github.com/alaric/crev-proofs.git
Fetching https://github.com/alaric/crev-proofs.git... OK
Found proofs from:
 /d/d/c/async_executors    cargo crev repo fetch url https://github.com/dmerejkowsky/crev-proofs.git
Fetching https://github.com/dmerejkowsky/crev-proofs.git... Failed processing a proof: Verification equation was not satisfied
OK
Failed processing a proof: Verification equation was not satisfied
Found proofs from:
 /d/d/c/async_executors    cargo crev repo fetch url https://github.com/dmerejkowsky/crev-proofs.git
Failed processing a proof: Verification equation was not satisfied
Fetching https://github.com/dmerejkowsky/crev-proofs.git... Failed processing a proof: Verification equation was not satisfied
OK
Failed processing a proof: Verification equation was not satisfied
Found proofs from:
 /d/d/c/async_executors    cargo crev repo fetch url https://github.com/roblabla/crev-proofs.git
Failed processing a proof: Verification equation was not satisfied
Fetching https://github.com/roblabla/crev-proofs.git... OK; 1 new trust proofs; 1 new package reviews
Found proofs from:
       2 b5KVguZFzGkZ-ZFynEYB7ttSIOK5pW8sRXlUMZ8U6Ik
 /d/d/c/async_executors    cargo crev repo fetch url https://github.com/Canop/crev-proofs.git
Failed processing a proof: Verification equation was not satisfied
Fetching https://github.com/Canop/crev-proofs.git... OK; 1 new trust proofs; 6 new package reviews
Found proofs from:
       7 FBkykBV6YaqAaGoUXyvd-XkEqDYxQNM7EUnZ2nuy-XQ
 /d/d/c/async_executors    cargo crev repo fetch url https://github.com/oherrala/crev-proofs.git
Failed processing a proof: Verification equation was not satisfied
Fetching https://github.com/oherrala/crev-proofs.git... OK
Found proofs from:
       4 YWfa4SGgcW87fIT88uCkkrsRgIbWiGOOYmBbA1AtnKA
 /d/d/c/async_executors    cargo crev repo fetch url https://github.com/flodiebold/crev-proofs.git
Failed processing a proof: Verification equation was not satisfied
Fetching https://github.com/flodiebold/crev-proofs.git... OK; 1 new trust proofs; 1 new package reviews
Found proofs from:
       2 sY_GYmASW7W-hSOZe78C0xbOTAYJM-vZNO8ktIAjvmw
 /d/d/c/async_executors    cargo crev repo fetch url https://github.com/qnighy/crev-proofs.git
Failed processing a proof: Verification equation was not satisfied
Fetching https://github.com/qnighy/crev-proofs.git... OK; 2 new trust proofs; 5 new package reviews
Found proofs from:
       7 fkkJ3Z6xSDEZwFlyKgIDxYS2x6mS7b2cxbWBeEWgfXs
 /d/d/c/async_executors    cargo crev repo fetch url https://github.com/bash/crev-proofs.git
Failed processing a proof: Verification equation was not satisfied
Fetching https://github.com/bash/crev-proofs.git... OK; 8 new package reviews
Found proofs from:
       8 Mw3ReGwT2pB41AUQ12T7TcgvH5pq7I1gd8Iw_LLH4XQ
 /d/d/c/async_executors    cargo crev repo fetch url https://github.com/sgeisler/crev-proofs.git
Failed processing a proof: Verification equation was not satisfied
Fetching https://github.com/sgeisler/crev-proofs.git... Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
OK
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Found proofs from:
 /d/d/c/async_executors    cargo crev repo fetch url https://github.com/otavio/crev-proofs.git
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Fetching https://github.com/otavio/crev-proofs.git... Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
OK
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Found proofs from:
 /d/d/c/async_executors    cargo crev repo fetch url https://github.com/frigus02/crev-proofs.git
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Fetching https://github.com/frigus02/crev-proofs.git... OK; 1 new trust proofs
Found proofs from:
       1 X1C7o04N0lyKCiyQ1UhM5kbsuqjTVsSu4kOgth8DI1A
 /d/d/c/async_executors    cargo crev repo fetch url https://github.com/cyplo/crev-proofs.git
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Fetching https://github.com/cyplo/crev-proofs.git... OK; 1 new package reviews
Found proofs from:
       1 c1DBeLoxyO5CDu6-eA5mU4wg4ZDlDqKm2eqo1mR8qeQ
 /d/d/c/async_executors    cargo crev repo fetch url https://github.com/HeroicKatora/crev-proofs.git
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Fetching https://github.com/HeroicKatora/crev-proofs.git... OK; 6 new trust proofs; 16 new package reviews
Found proofs from:
      22 -sApEowWcAS9J0R7aO18cghvhLBpuMhyeUuWQq_fits
 /d/d/c/async_executors    cargo crev repo fetch url https://github.com/vi/crev-proofs.git
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Fetching https://github.com/vi/crev-proofs.git... Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
OK
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Failed processing a proof: Verification equation was not satisfied
Found proofs from:
```

**Comment by dpc** [comment] 2020-04-27 03:15
I'm currently traveling, but will look into it when I'm back. You can try asking people in the chatrooms in the meantime. Thanks!

**Comment by dpc** [comment] 2020-04-29 16:34
Some of the repos you're importing are really old (e.g. https://github.com/dmerejkowsky/crev-proofs) and at some point a while ago we've changed a signing crypto to be more "standard".

See https://github.com/crev-dev/cargo-crev/wiki/List-of-Proof-Repositories#pre-v06-repositories

There's not much to do other than no using them (or asking their author to update as per instruction in the above link). You can delete them from your cache (somewhere in `~/.cache/crev/remotes/` on Linux).

**Comment by dpc** [comment] 2020-04-29 16:35
`crev` will ignore such proofs and work otherwise normally, but will print that annoying message. We could possibly improve that message (print it only once, point to a file, etc.)

**Comment by najamelan** [comment] 2020-04-29 18:28
Thanks for looking into it. 

> We could possibly improve that message (print it only once, point to a file, etc.)

Yes maybe point it out at the moment of fetch, and not actually import them if they aren't valid and usable anyway. That way the cache doesn't get into a bad state? 

I imported those by searching github for "crev-proofs", as I didn't see any other way of obtaining reviews in the getting started guide... Is there some better proof discovery mechanism that I'm missing?

How would I go about identifying the culprits in `~/.cache/crev/remotes` to removing them?

**Comment by dpc** [comment] 2020-04-29 18:41
Surprisingly on my system I'm getting an exact path to a file where the things did not parse well, so it was easily to clean it up. Maybe try upgrading to 0.17 that I've just released?

It's hard to just "not fetch" because the repo can be full of valuable reviews, and only one file does not parse well for some reason, and throwing the whole repo seem wasteful.

**Comment by najamelan** [comment] 2020-04-29 18:59
Ok, 

version 0.17 shows the paths. I will remove them. I'm wondering, since these are git repo's, how would that play if I later did `cargo crev repo fetch all`?

Since git is kind of set in stone, maybe it's better to show the warning only on:
- fetch
- when CrevID == Self

with some explanation of what to do and just ignore those proofs in other situations?

**Comment by najamelan** [comment] 2020-04-29 19:12
Issue solved for now, I have one error left when querying the reviews for a crate:
`Failed scanning for proofs: Error iterating local ProofStore at /home/user/.config/crev/proofs: IO error for operation on /home/user/.config/crev/proofs: No such file or directory (os error 2)`

I imagine that's because I have not made a CrevID nor any proofs? If that's the case, it would seem that nothing is wrong, so maybe no error needs to be printed for that.

So running fetch all does bring them back. :-(

**Comment by dpc** [comment] 2020-04-29 19:38
That looks like a bug, yes.

**Comment by dpc** [comment] 2020-05-24 06:54
> I imagine that's because I have not made a CrevID nor any proofs?

`master` now contains a fix for  this.

I'm closing, since I don't think there's anything more actionable. If you haven't signed any trust proofs for that ID with old proof formats, you can just delete that directory from cache. If you did, you will also have to delete that proof (manually).

Feel free to reopen or ask any more questions.

**Closed by dpc** 2020-05-24 06:54 UTC

**Comment by LucianoBestia** [comment] 2020-05-26 11:40
I am working on a web interface for cargo-crev: 
https://bestia.dev/cargo_crev_web/info/group_by_author/

And I hope I will eventually add all the review authors.
I stumbled into the same problem when trying to add repos ".../crev-proofs" and found a lot of old or incomplete repos on github.
With a lot of :
Failed processing a proof: Verification equation was not satisfied
I will try to use the new release now.

**Comment by dpc** [comment] 2020-05-26 19:08
> With a lot of : "Failed processing a proof: Verification equation was not satisfied"

Handling of this error has not been changed. Only `Failed scanning for proofs: Error iterating local ProofStore at /home/user/.config/crev/proofs: IO error for operation on /home/user/.config/crev/proofs: No such file or directory (os error 2)` was.

I'm not sure if I should just silence this error or what. The problem is that some repos are stale and have proof formats that were rendered incompatible a long time ago.
